variables:
  GIT_STRATEGY: clone
  APP_ENV_FILE: /path/to/production/env.file # Can be injected using gitlab CI variables

stages:
  - test
  - deploy

.install-deps-template: &install-deps
  before_script:
    - echo "Installing deps"
    - python3 -m pip install poetry
    - poetry install -vv

run_tests:
  <<: *install-deps
  stage: test
  tags:
    - testing
  script:
    - poetry run pre-commit run --all-files
    - poetry run dotenv -f envs/test.env run pytest -vv --cov=src

deploy_app:
  <<: *install-deps
  stage: deploy
  only: ['master']
  tags:
    - production
  script:
    - poetry run dotenv -f "${APP_ENV_FILE}" run alembic upgrade head;
    - sh deploy.sh
  environment:
    name: production