# Local docker-compose configuration

version: '3.7'

services:
  back:
    container_name: {{ cookiecutter.project_name }}_backend
    build:
      context: .
      target: development
      labels:
        detector.description: {{ cookiecutter.project_description }}
    env_file:
      - envs/.env
    ports:
      - 8401:8000
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - {{ cookiecutter.project_name }}_network

  db:
    container_name: {{ cookiecutter.project_name }}_db
    image: postgres:12.4
    volumes:
      - {{ cookiecutter.project_name }}_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - {{ cookiecutter.project_name }}_network
    env_file:
      - envs/.env

  redis:
    container_name: {{ cookiecutter.project_name }}_redis
    image: bitnami/redis:6.0.7
    volumes:
      - {{ cookiecutter.project_name }}_redis_data:/bitnami/redis/data
    env_file:
      - envs/.env
    ports:
      - 6379:6379
    networks:
      - {{ cookiecutter.project_name }}_network

volumes:
  {{ cookiecutter.project_name }}_db_data:
  {{ cookiecutter.project_name }}_redis_data:

networks:
  {{ cookiecutter.project_name }}_network:
    name: {{ cookiecutter.project_name }}_network